### ISSUE TITLE
Problema di auto livellamento 

### ISSUE THREAD

**Issue by boromyr** [BsCmOD/Alfawise-U30Pro-hack-and-mod#1]
Ciao, come da titolo ho un problema con il livellamento del letto di stampa con il bltouch. Uso una LK4 Pro.
Il problema in pratica consiste in un bug del Z OFFSET, il quale risulta errato di 0,4mm. 
Ho provato sia usando la procedura guidata creata da te dal touchscreen, sia facendo tutto manualmente tramite Pronterface. Chiamando un G28 Z0, taro dunque l'asse Z, il quale dopo ritorna in posizione 5(o 10, dipende dal valore scelto), e, subito dopo, lo screen si aggiorna da solo a 5.4. Altre volte il problema non si presenta, e stampa perfettamente, altre volte l'ugello va fuori scala di qualche mm, trovandosi in aria o a strisciare sul letto di stampa.
Ho provato usando il file Configuration.h sia quello fornito da te, sia quello della Longer che quello modicato da me.
Hai riscontrato questo problema o sapresti aiutarmi a risolverlo?
Grazie.

Altri bug minori ma non invalidanti che ho riscoltrato sono:
* la regolazione delle nuove funzioni è difficile in quanto circa 1 colpo su 4 viene letto dalla LK4
* l'opzione dei babystpping è fantastica per correggere in tempo reale la stampa, ma lo schermo non si aggiorna con la nuova posizione
* qualche altro piccolo problema di refresh in generale

**Comment by BsCmOD** [comment]
Allora, riguardo l'altezza di Z "sfasato" prova ad agire con il comand M851 Z-0.4 (visto che hai uno scarto di 0,4mm) almeno mi pare di capire che il tuo problema sia questo. Di che guida parli? Quella sul gruppo Alfawise Italia su Facebook? Perdonami ma non riesco a ricordami tutto... Poi per i bug...

1. lo so, a volte è lunga a rispondere ai comandi, questo, difficilmente è risolvibile perchè già il firmware originale si mangia il 79% di RAM (purtroppo la scheda originale monta un AtMega2560 a 8bit) ed aggiungendo un paio di cavolate come l'ABL bilineare e qualche funzione in più per gestire i valori dallo schermo arriva ad occupare l'81% di RAM portando la scheda ad essere un pò ingolfata e a rispondere in ritardo oltre a fare qualche movimento "scattoso" durante la stampa. C'è poco da fare purtroppo...

2. Questo mi pare alquanto strano perchè l'ho usata pure io questa funzione e l'hanno usata in molti nel gruppo Alfawise Italia ma, protrebbe essere legato al problema del punto 1. Ecco il valore visualizzato dell'asse Z quasi sicuramente lo visualizzaerai in maniera scorretta... ci abbiamo lavorato 15 giorni in 2 per tentare di risolvere questo problema ma ahimè... invano.

3. eh eh eh... come sopra purtroppo....

**Comment by boromyr** [comment]
Mi sono dimenticato a specificare che ho misurato il mio Z OFFSET ed equivale a -2.9, ovviamente aggiunto in memoria prima del livellamento. Dunque questo errore che si presenta si va ad aggiungere al valore già salvato, portando l'offset a -3.4 o -2.3. Riguardo la procedura guidata mi riferivo alla funzione creata da te e inserita nella sezione Utilities.
Per il resto ovviamente ci dobbiamo accontentare delle prestazioni che può offrire l'AtMega

**Comment by BsCmOD** [comment]
> 
> 
> Mi sono dimenticato a specificare che ho misurato il mio Z OFFSET ed equivale a -2.9, ovviamente aggiunto in memoria prima del livellamento. Dunque questo errore che si presenta si va ad aggiungere al valore già salvato, portando l'offset a -3.4 o -2.3. Riguardo la procedura guidata mi riferivo alla funzione creata da te e inserita nella sezione Utilities.
> Per il resto ovviamente ci dobbiamo accontentare delle prestazioni che può offrire l'AtMega

Oddio non mi ricordo ora che procedura ho riportato li... non ho più la scheda originale ora... per la taratura guarda questo documento dal paragrafo 8 "Taratura": https://drive.google.com/open?id=1N2rlx_nmoFSlUMrkkykG_vAnWYEKNMYa anche se riguarda il sensore capacitivo il discorso pressapoco è lo stesso

**Comment by boromyr** [comment]
Dopo aver fatto molti test sono riuscito a isolare il problema, il mio 3DTouch è difettoso, il problema non era nel tuo firmware, mi dispiace averti disturbato invano, avevo dato per scontato che il sensore fosse perfettamente funzionate. In ogni caso il tuo documento mi ha aiutato a capire meglio il meccanismo dell'auto livellamento. Solo un dubbio: il comando M420 S1 è dunque essenziale? Molti non lo citano.

Inoltre, non usando una barra led ho provato con successo a editare il codice per mandare comandi personalizzati. Ho provato un semplice G28, che è stato eseguito correttamente, dunque è possibile aggiungere macro personalizzate per chi non usa le barre led.
 
Un'ultima domanda: oltre i file LGT hai modificato altri file del firmware che sono essenziali per le funzionalità dello schermo?

Grazie di tutto!!!

**Comment by BsCmOD** [comment]
> Dopo aver fatto molti test sono riuscito a isolare il problema, il mio 3DTouch è difettoso, il problema non era nel tuo firmware, mi dispiace averti disturbato invano, avevo dato per scontato che il sensore fosse perfettamente funzionate. In ogni caso il tuo documento mi ha aiutato a capire meglio il meccanismo dell'auto livellamento. Solo un dubbio: il comando M420 S1 è dunque essenziale? Molti non lo citano.
> 
> Inoltre, non usando una barra led ho provato con successo a editare il codice per mandare comandi personalizzati. Ho provato un semplice G28, che è stato eseguito correttamente, dunque è possibile aggiungere macro personalizzate per chi non usa le barre led.
> 
> Un'ultima domanda: oltre i file LGT hai modificato altri file del firmware che sono essenziali per le funzionalità dello schermo?
> 
> Grazie di tutto!!!

Tranquillo, il malfunzionamento è sempre dietro l'angolo, può succedere. Il comando M420 S1 teoricamente non serve ma cmq anche se viene inserito lo stesso nello start gcode male non fa. Questa è la spiegazione ufficiale del funzionamento dell'abl dal sito di Marlin: https://marlinfw.org/docs/gcode/G029-abl.html
Poi, per quanto riguarda il firmware i file che ho modificato e che gestiscono le funzioni dello schermo sono LGT_SCR.cpp e LGT_MACRO.h inoltre c'è una piccola modifica nel file che gestisce la SD che dovrebbe calcolare e conteggiare il tempo rimanente e visualizzarlo a schermo funzione che ho levato subito perché non lavora come dovrebbe ma, nel file la riga quasi sicuramente è rimasta, anche se c'è comunque non comporta nessun problema.
