### ISSUE TITLE
Any changes

### ISSUE THREAD

**Issue by gonjnunes** [BsCmOD/Alfawise-U30Pro-hack-and-mod#2]
I use Longer LK4 Pro screen firmware, on about menu firmware are updated but in menus any changes appear. I put twin_set on 8gb card process its short, what I do wrong?

**Comment by BsCmOD** [comment]
Nope, you're procedure it's right, what file are you using? It's possible there's something wrong and you have finded a possible issue 😅

**Comment by gonjnunes** [comment]
I use all content of this rar file Longer "LK4Pro screen firmware.rar". But its the same on others I think I use all.

**Comment by BsCmOD** [comment]
Ok I've done a rapid check... When you had tried to update you touch screen during the updating process did a blue screen appear with some white words with counters and the varius screens scrolls during all procedure?

**Comment by gonjnunes** [comment]
Yes 
blue screen 
[https://mega.nz/file/2nwQ0IjC#6flyTwIBmLJdqrPS6pj5mW-p0-VYHjMw7hm-gQZnu44](url)
About screen
[https://mega.nz/file/6yhADSLY#wZcMo6yqHE70RX5_-fYQe2x7D2FThfVu8n86OFvBRh4](url)

**Comment by BsCmOD** [comment]
Ok, blue screen but all the counters remains to zero, try with another microsd it isn't the first time that this happen even if there's something strange because the about screen it's correct
