### ISSUE TITLE
Aiuto per comprendere il firmware del Display LK4pro

### ISSUE THREAD

**Issue by iw5edv** [BsCmOD/Alfawise-U30Pro-hack-and-mod#3]
Ciao potresti aiutarmi a comprendere il firmware del display della LK4pro. 
In modo da mettermi al lavoro per migliorarlo ed implementare nuove funzioni.

**Comment by BsCmOD** [comment]
Allora... sostanzialmente il firmware gira su di una serie di schermate formate da semplici file BMP sulle quali vengono sovrapposte della aree "touch" che vengono gestite mediante il software DWIN DGUS che trovi con il codice sorgente, non serve installarlo, basta estrarlo, eseguirlo e aprire il file del progetto. Ora, una volta chiarito il fatto che in ogni schermata ti troverai delle aree touch il difficile arriva ora... allora un'area sensibile può portarti ad un altra schermata semplicemente rimandandoti ad un altra immagine presente nella lista o, può eseguire un determinato comando. Ogni comando ha un suo "indice" che a sua volte rimanda poi alla funzione. Mi spiego, il tastino che alza Z ad esempio, ha come indice VP 1002 che rimanda alla funzione presente nel file marlin LGT_MACRO.h che  sua volta rimanda verso l'ebutton 000E (gli ebutton sono numerati in esadecimale) sempre presente nello stesso file che infine rilancia al comando vero e proprio presente nel file LGT_SCR.h... è un pò incasinato ma insomma studiandoci un pò si fa... poi c'è una magagna non da poco legata alla generazione dei nomi di alcuni file di configurazione creati da DWIN DGUS in particolare: 13触控配置文件.bin e
14变量配置文件.bin che devono essere rinominati come 13.bin e 14.bin altrimenti lo schermo non si caricherà la nuova configurazione...

**Comment by iw5edv** [comment]
Grazie mille. Non riuscivo a comprendere il mccanismo "perverso" di dove erano scritti i comendi o come faceva a richiamare le macro.
Sei stato chiarissimo ora ci studio e vediamo se riesco a combinare qualcosa.
Nel caso faccio un fork del tuo repository.
Buona giornata.

**Comment by BsCmOD** [comment]
Eh eh eh effettivamente è un sistema abbastanza intricato però una volta capito non è poi così complicato... Ci ho messo quasi un mese a capire come funzionasse il tutto... Per il resto d'accordo, creati il fork se riesci a fare un menu fatto meglio ben venga 😉

**Comment by BsCmOD** [comment]
Ah un altra cosa le schermate prima di caricarle nello schermo vano girate di 90 gradi a sinistra non vanno lasciate in verticale
